In [25]:
import pandas as pd
s = pd.Series([1,2,3,4,5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
s1 = pd.Series([4,5,6,7,8], index = ['a','b','c','d','e'], name = 'num')
print(s1)

a    4
b    5
c    6
d    7
e    8
Name: num, dtype: int64

In [8]:
print(s[3])

4

In [10]:
print(s1['c'])

6

In [24]:
#dataframe
import numpy as np
d = np.random.randint(4,10,(3,4))
d1 = pd.DataFrame(d,columns = ['a','b','c','d'])
d1

   a  b  c  d
0  4  8  8  4
1  7  7  8  7
2  8  5  5  8

In [23]:
d = np.random.randint(4,10,(3,4))
d1 = pd.DataFrame(d,columns = ['a','b','c','d'], index=['kk','pp','oo'])
d1

    a  b  c  d
kk  5  7  8  5
pp  9  6  8  8
oo  4  9  8  4

In [22]:
#list to data frame
l = [1,2,3,4,5]
l1= pd.DataFrame(l,columns =['vv'], index = ['a','b','c','d','e'])
l1

   vv
a   1
b   2
c   3
d   4
e   5

In [21]:
l = [['varun',1],['jacob',2],['cindy',3],['yakob',4],['jacob',5]]
l2= pd.DataFrame(l,columns =['vv','cc'])
l2

      vv  cc
0  varun   1
1  jacob   2
2  cindy   3
3  yakob   4
4  jacob   5

In [27]:
#dict to df
q= {'enployee':['p','o','l','k'], 'slaray':['1','2','3','4']}
q1 = pd.DataFrame(q)
q1

  enployee slaray
0        p      1
1        o      2
2        l      3
3        k      4

In [31]:
q2 = {'employee': pd.Series([10,20,30,40]),'salary': pd.Series([400,50,66,4949])}
q3 = pd.DataFrame(q2)
q3

   employee  salary
0        10     400
1        20      50
2        30      66
3        40    4949

In [35]:
q4 = [{'a':1,'b':2,'c':3},{'a':3,'b':8,'c':9}]
q5 = pd.DataFrame(q4)
q5

   a  b  c
0  1  2  3
1  3  8  9

In [40]:
q6 = [{'a':1,'b':2,'c':3},{'y':3,'b':8,'c':9}]
q7 = pd.DataFrame(q6, index = ['pp','oo'])
q7

      a  b  c    y
pp  1.0  2  3  NaN
oo  NaN  8  9  3.0

In [44]:
l1=['pri','eor','epri','krhf']
l2 = [4,5,6,7]
l= list(zip(l1,l2))
l3 = pd.DataFrame(l,columns =['pp','hh'])
l3

     pp  hh
0   pri   4
1   eor   5
2  epri   6
3  krhf   7

In [45]:
ll1={'names': ['pri','eor','epri','krhf','dhf','djd','wfsf'], 'marks1': [12,2,3,4,5,9,6], 'marks2': [12,3,34,45,66,77,45]}
ll2= pd.DataFrame(ll1) # keys is coulms and data is values
ll2

  names  marks1  marks2
0   pri      12      12
1   eor       2       3
2  epri       3      34
3  krhf       4      45
4   dhf       5      66
5   djd       9      77
6  wfsf       6      45

In [49]:
students = [f'students{i}' for i in range(1,11)]
subjects = ['maths','phy','chem']
marks = np.random.randint(1,10, size = (8,3))
g= pd.DataFrame(marks, columns = subjects) # if students is not given
g

   maths  phy  chem
0      3    5     7
1      7    7     9
2      4    5     5
3      7    8     4
4      2    1     5
5      5    8     3
6      6    9     6
7      6    1     4

In [55]:
students = [f'student{i}' for i in range(1,11)]
subjects = ['maths','phy','chem']
marks = np.random.randint(1,10, size = (10,3))
g= pd.DataFrame(marks, columns = subjects) 
g.insert(0,'student marks',students) # 0 is the index of the column
print(g)

  student marks  maths  phy  chem
0      student1      6    5     2
1      student2      9    7     8
2      student3      6    2     3
3      student4      2    5     1
4      student5      3    4     3
5      student6      8    7     4
6      student7      4    4     5
7      student8      6    4     2
8      student9      8    6     6
9     student10      4    5     3

In [60]:
students = ['asnjf','dnjn','dnjn','denn','ejionc','ednj','endndn','dcon','pri','eor','epri','krhf','dhf','djd','wfsf','ll','p','o','l','k']
marks = np.random.randint(1,99, size = (20,3)) 
p = pd.DataFrame(marks, columns = ['maths','science','eng'])
p.insert(0,'student_names', students)
print(p)
p.to_csv('stdents_marks.csv', index = False)

   student_names  maths  science  eng
0          asnjf     17       83   38
1           dnjn      1       57   40
2           dnjn     56       25   97
3           denn     26       95   88
4         ejionc      2       52   12
5           ednj     43       33   43
6         endndn     43       27   59
7           dcon     86       78   80
8            pri     74       87   63
9            eor     33       26    7
10          epri     55       84   19
11          krhf     51       34   14
12           dhf     10       31   95
13           djd     25       53    8
14          wfsf     78       18   48
15            ll      5       48   44
16             p     13       63   90
17             o     66       35   62
18             l     93       59   72
19             k     96       28   88

In [61]:
list(p.index)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [75]:
j = np.random.randn(100,5) # normal distribution btw 0 to 1 rows = 20 and columns = 3
j1 = pd.DataFrame(j, columns=['a','b','c','d','e'])
j1

           a         b         c         d         e
0  -0.362729  0.113541  0.225345 -0.494219 -0.114814
1  -0.851071 -0.294440  0.853059 -0.615779  0.542488
2   1.292906 -0.315313  0.707852 -0.494924  1.487257
3  -1.219688  1.825510  1.326137  1.712857  0.254717
4  -0.008659 -0.571988  0.471138 -0.720304  1.181975
..       ...       ...       ...       ...       ...
95  1.780001 -0.686647  0.331336  0.967466  0.183953
96 -1.115360 -1.026723 -1.037263  0.311246  0.022972
97  0.200576  0.100657  2.395968 -0.358461 -1.180520
98  0.206272  0.289444 -1.735614 -0.441546  1.556254
99  1.721284 -0.294623  1.881424  0.877858 -0.038824

[100 rows x 5 columns]

In [76]:
j1.head()

          a         b         c         d         e
0 -0.362729  0.113541  0.225345 -0.494219 -0.114814
1 -0.851071 -0.294440  0.853059 -0.615779  0.542488
2  1.292906 -0.315313  0.707852 -0.494924  1.487257
3 -1.219688  1.825510  1.326137  1.712857  0.254717
4 -0.008659 -0.571988  0.471138 -0.720304  1.181975

In [77]:
j1.head(10)

          a         b         c         d         e
0 -0.362729  0.113541  0.225345 -0.494219 -0.114814
1 -0.851071 -0.294440  0.853059 -0.615779  0.542488
2  1.292906 -0.315313  0.707852 -0.494924  1.487257
3 -1.219688  1.825510  1.326137  1.712857  0.254717
4 -0.008659 -0.571988  0.471138 -0.720304  1.181975
5 -0.665391  0.388419  0.361824  0.215551  0.382981
6  1.803512  0.742658  2.338235 -1.328280 -0.173308
7  0.584131  0.584118  0.906951  0.567832 -0.822575
8 -0.792497 -0.784048  0.041950  1.133370 -0.807082
9  0.043704  0.242493  0.009403 -1.262395  0.217177

In [78]:
j1.tail()

           a         b         c         d         e
95  1.780001 -0.686647  0.331336  0.967466  0.183953
96 -1.115360 -1.026723 -1.037263  0.311246  0.022972
97  0.200576  0.100657  2.395968 -0.358461 -1.180520
98  0.206272  0.289444 -1.735614 -0.441546  1.556254
99  1.721284 -0.294623  1.881424  0.877858 -0.038824

In [79]:
j1.tail(10)

           a         b         c         d         e
90 -0.857071  0.969797 -0.048796 -1.959817 -1.358475
91  1.245488 -0.426804  0.056758 -0.921320 -0.052374
92 -0.426017  2.202681 -0.446971 -0.625516  1.272849
93 -0.621553 -1.030030  0.553583  0.185277 -0.095185
94  0.765547  0.366719  0.458131 -1.213915  0.807318
95  1.780001 -0.686647  0.331336  0.967466  0.183953
96 -1.115360 -1.026723 -1.037263  0.311246  0.022972
97  0.200576  0.100657  2.395968 -0.358461 -1.180520
98  0.206272  0.289444 -1.735614 -0.441546  1.556254
99  1.721284 -0.294623  1.881424  0.877858 -0.038824

In [80]:
list(j1.columns)

['a', 'b', 'c', 'd', 'e']

In [81]:
j1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       100 non-null    float64
 1   b       100 non-null    float64
 2   c       100 non-null    float64
 3   d       100 non-null    float64
 4   e       100 non-null    float64
dtypes: float64(5)
memory usage: 4.0 KB

In [82]:
j1.describe()

                a           b           c           d           e
count  100.000000  100.000000  100.000000  100.000000  100.000000
mean     0.131319   -0.041601    0.026893   -0.019105   -0.100321
std      1.122132    1.019272    1.080591    0.929626    1.009606
min     -2.341810   -2.554939   -2.508656   -1.959817   -2.609920
25%     -0.667931   -0.732704   -0.722786   -0.659516   -0.810956
50%      0.191293    0.023574   -0.005580    0.005690   -0.097441
75%      0.897461    0.585517    0.604306    0.637938    0.547952
max      2.763862    2.492607    2.553831    2.775678    1.983148

In [84]:
j1.rename(columns={'a':'jj','d':'pp'},inplace = True)
j1

          jj         b         c        pp         e
0  -0.362729  0.113541  0.225345 -0.494219 -0.114814
1  -0.851071 -0.294440  0.853059 -0.615779  0.542488
2   1.292906 -0.315313  0.707852 -0.494924  1.487257
3  -1.219688  1.825510  1.326137  1.712857  0.254717
4  -0.008659 -0.571988  0.471138 -0.720304  1.181975
..       ...       ...       ...       ...       ...
95  1.780001 -0.686647  0.331336  0.967466  0.183953
96 -1.115360 -1.026723 -1.037263  0.311246  0.022972
97  0.200576  0.100657  2.395968 -0.358461 -1.180520
98  0.206272  0.289444 -1.735614 -0.441546  1.556254
99  1.721284 -0.294623  1.881424  0.877858 -0.038824

[100 rows x 5 columns]

In [87]:
data = pd.read_csv('company_sales_data.csv')
data

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit
0,1,2500,1500,5200,9200,1200,1500,21100,211000
1,2,2630,1200,5100,6100,2100,1200,18330,183300
2,3,2140,1340,4550,9550,3550,1340,22470,224700
3,4,3400,1130,5870,8870,1870,1130,22270,222700
4,5,3600,1740,4560,7760,1560,1740,20960,209600
5,6,2760,1555,4890,7490,1890,1555,20140,201400
6,7,2980,1120,4780,8980,1780,1120,29550,295500
7,8,3700,1400,5860,9960,2860,1400,36140,361400
8,9,3540,1780,6100,8100,2100,1780,23400,234000
9,10,1990,1890,8300,10300,2300,1890,26670,266700
10,11,2340,2100,7300,13300,2400,2100,41280,412800
11,12,2900,1760,7400,14400,1800,1760,30020,300200

In [88]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   month_number  12 non-null     int64
 1   facecream     12 non-null     int64
 2   facewash      12 non-null     int64
 3   toothpaste    12 non-null     int64
 4   bathingsoap   12 non-null     int64
 5   shampoo       12 non-null     int64
 6   moisturizer   12 non-null     int64
 7   total_units   12 non-null     int64
 8   total_profit  12 non-null     int64
dtypes: int64(9)
memory usage: 996.0 bytes

In [89]:
data.head()

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit
0,1,2500,1500,5200,9200,1200,1500,21100,211000
1,2,2630,1200,5100,6100,2100,1200,18330,183300
2,3,2140,1340,4550,9550,3550,1340,22470,224700
3,4,3400,1130,5870,8870,1870,1130,22270,222700
4,5,3600,1740,4560,7760,1560,1740,20960,209600

In [90]:
data.describe()

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.00000,12.000000
mean,6.500000,2873.333333,1542.916667,5825.833333,9500.833333,2117.500000,1542.916667,26027.50000,260275.000000
std,3.605551,584.595172,316.733745,1242.032486,2348.095779,617.724931,316.733745,7014.36594,70143.659404
min,1.000000,1990.000000,1120.000000,4550.000000,6100.000000,1200.000000,1120.000000,18330.00000,183300.000000
25%,3.750000,2460.000000,1305.000000,4862.500000,8015.000000,1795.000000,1305.000000,21065.00000,210650.000000
50%,6.500000,2830.000000,1527.500000,5530.000000,9090.000000,1995.000000,1527.500000,22935.00000,229350.000000
75%,9.250000,3435.000000,1765.000000,6400.000000,10045.000000,2325.000000,1765.000000,29667.50000,296675.000000
max,12.000000,3700.000000,2100.000000,8300.000000,14400.000000,3550.000000,2100.000000,41280.00000,412800.000000