In [1]:
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC # svm - support vector machine , svc - support vector classification
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
iris = datasets.load_iris()

In [3]:
df = pd.DataFrame(data = iris.data, columns = iris.feature_names)

In [4]:
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [5]:
df['target'] = iris.target # add a column named target to the dataset
df['target_name'] = iris.target_names[iris.target] # add a column name called target_name to the dataset that contains the actual name corresponding to those numbers.
df # general syntax - df['column_name'] = values

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,target_name
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2,virginica
146,6.3,2.5,5.0,1.9,2,virginica
147,6.5,3.0,5.2,2.0,2,virginica
148,6.2,3.4,5.4,2.3,2,virginica
149,5.9,3.0,5.1,1.8,2,virginica

In [6]:
x= iris.data
y = iris.target

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [8]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.fit_transform(x_test)

In [9]:
svm_model = SVC(kernel ='rbf' , C = 1.0, gamma = 'scale') #kernal = 'rbf - a data cannot be always seperated by straight line because the data may be mixed together so in that caxes we uses rbf to create a non-linear decision boundary.
# c - determines how strightly the model tries to classify the training data points correctly. small c - little mistakes is fine, larger(simple boundary) c - tries harder to avoid mistakes(comples boundary), c = 1.0 is the default
# gamma - controls how much influence the datapoints have(over prediction). higher gamma - each datapoint have local influence(complex boundary), lowe gamma - each datapoint have wider influence(smoother boundary)
svm_model.fit(x_train_scaled, y_train)

SVC()

Setosa is linearly separable.

Versicolor and Virginica overlap slightly — not fully separable by a straight line.
Hence, the RBF kernel allows the SVM to form a curved decision boundary that correctly separates these two species.

In [10]:
y_pred = svm_model.predict(x_test_scaled)

In [11]:
print('Training accuracy:', svm_model.score(x_train_scaled, y_train))
print('Test Accuracy:', svm_model.score(x_test_scaled, y_test))

Training accuracy: 0.9666666666666667
Test Accuracy: 0.9666666666666667

In [16]:
print('accuracy score', accuracy_score(y_test, y_pred))
print('confusion matrix\n', confusion_matrix(y_test, y_pred))
print('classification report\n', classification_report(y_test, y_pred))

accuracy score 0.9666666666666667
confusion matrix
 [[10  0  0]
 [ 0  9  0]
 [ 0  1 10]]
classification report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.90      1.00      0.95         9
           2       1.00      0.91      0.95        11

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

In [17]:
test_results = pd.DataFrame(scaler.inverse_transform(x_test_scaled),columns = iris.feature_names)
test_results['actual flower'] = iris.target_names[y_test] # here y_test contains only target name(because traget column), but we need target name so we used this code.
#this add a new column names actual flowet
test_results['predicted_flower'] = iris.target_names[y_pred]

In [19]:
print(test_results) #To see each test(only contains test data) flower's original measurements, its actual species, and the species predicted by your SVM model.

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 6.1               2.8                4.7               1.2
1                 5.7               3.8                1.7               0.3
2                 7.7               2.6                6.9               2.3
3                 6.0               2.9                4.5               1.5
4                 6.8               2.8                4.8               1.4
5                 5.4               3.4                1.5               0.4
6                 5.6               2.9                3.6               1.3
7                 6.9               3.1                5.1               2.3
8                 6.2               2.2                4.5               1.5
9                 5.8               2.7                3.9               1.2
10                6.5               3.2                5.1               2.0
11                4.8               3.0                1.4               0.1
12                5.5               3.5                1.3               0.2
13                4.9               3.1                1.5               0.1
14                5.1               3.8                1.5               0.3
15                6.3               3.3                4.7               1.6
16                6.5               3.0                5.8               2.2
17                5.6               2.5                3.9               1.1
18                5.7               2.8                4.5               1.3
19                6.4               2.8                5.6               2.2
20                4.7               3.2                1.6               0.2
21                6.1               3.0                4.9               1.8
22                5.0               3.4                1.6               0.4
23                6.4               2.8                5.6               2.1
24                7.9               3.8                6.4               2.0
25                6.7               3.0                5.2               2.3
26                6.7               2.5                5.8               1.8
27                6.8               3.2                5.9               2.3
28                4.8               3.0                1.4               0.3
29                4.8               3.1                1.6               0.2

   actual flower predicted_flower
0     versicolor       versicolor
1         setosa           setosa
2      virginica        virginica
3     versicolor       versicolor
4     versicolor       versicolor
5         setosa           setosa
6     versicolor       versicolor
7      virginica        virginica
8     versicolor       versicolor
9     versicolor       versicolor
10     virginica        virginica
11        setosa           setosa
12        setosa           setosa
13        setosa           setosa
14        setosa           setosa
15    versicolor       versicolor
16     virginica        virginica
17    versicolor       versicolor
18    versicolor       versicolor
19     virginica        virginica
20        setosa           setosa
21     virginica       versicolor
22        setosa           setosa
23     virginica        virginica
24     virginica        virginica
25     virginica        virginica
26     virginica        virginica
27     virginica        virginica
28        setosa           setosa
29        setosa           setosa

In [20]:
import joblib # joblib - python library to save and load machine- learning models.
joblib.dump(svm_model, 'sm_model.pkl') #svm_model - my trained model , svm_model.pkl - model is saved as pkl(python pickle file)
joblib.dump(scaler, 'scaler,pkl') # scaler - the scaler i used above to scale the x_train, test, scaler.pkl - file is saved there

['scaler,pkl']

dump() = save,
load() = bring back/use the saved object.